### ISSUE TITLE
Why only padding tokens are generated after a period of training, but no words? 

### ISSUE THREAD

**Issue by greens007** [xu-shitong/diffusion-image-captioning#3]
Hi, shitong
I try to duplicate your work. But I got into some trouble. Why only padding tokens are generated after a period of training, but no words? Do you ever meet it before? Looking forward to your reply!

**Comment by xu-shitong** [comment]
Yes, the problem occurred when the rounding weight was too low(e.g. lower than 0.2), or learning rate was too high(e.g. higher than 5e-4).

**Comment by greens007** [comment]
> 

Thanks! I'll try it.
